TrajectoryPlannerROS:
  acc_lim_th: 3.2 
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  max_vel_x: 0.95
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4

  escape_vel: -0.1
  
  holonomic_robot: false

  #Since we're using a holonomic robot, we'll set the set of y velocities it will sample
  # y_vels: [-0.3, -0.1, 0.1, -0.3]

  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.05

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20

  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325

  dwa: false

  oscillation_reset_dist: 0.05

  prune_plan: true
