map_type: costmap

footprint: [[-0.15, -0.1], [-0.15, 0.1], [0.15, 0.1], [0.185, 0.0], [0.15, -0.1]]
footprint_padding: 0.05

obstacle_layer:
    obstacle_range: 3.0
    raytrace_range: 4.0
    min_obstacle_height: 0.0
    max_obstacle_height: 1.0
    observation_sources: laser
    enabled: true
    track_unknown_space: true
    laser:
        topic: base_scan
        sensor_frame: base_laser_link
        data_type: LaserScan
        clearing: true
        marking: true
        inf_is_valid: true

inflation_layer:
    enabled: true
    inflate_unknown: false
    inflation_radius: 0.45
    cost_scaling_factor: 15.0

static_layer:
    enabled: true
    map_topic: /map

# lethal_cost_threshold: 100








# #Voxel grid specific parameters
# origin_z: 0.0
# z_resolution: 0.2
# z_voxels: 10
# unknown_threshold: 9
# mark_threshold: 0

# #Set the tolerance we're willing to have for tf transforms
# transform_tolerance: 0.3

# #Obstacle marking parameters
# obstacle_range: 2.5
# max_obstacle_height: 2.0
# raytrace_range: 3.0

# #The footprint of the robot and associated padding

# #Cost function parameters
# inflation_radius: 0.55
# cost_scaling_factor: 10.0

# #The cost at which a cell is considered an obstacle when a map is read from the map_server
# lethal_cost_threshold: 100

# #Configuration for the sensors that the costmap will use to update a map
# observation_sources: base_scan
# base_scan: {data_type: LaserScan, expected_update_rate: 0.4,
#   observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
