#For full documentation of the parameters in this file, and a list of all the
#parameters available for DWAPlannerROS, please see
#http://www.ros.org/wiki/dwa_local_planner
DWAPlannerROS:
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  max_vel_x: 0.35
  min_vel_x: 0.01

  max_vel_y: 0.01
  min_vel_y: -0.01

  max_trans_vel: 0.35
  min_trans_vel: 0.01

  max_vel_theta: 1.0
  min_vel_theta: 0.05

  sim_time: 1.7
  sim_granularity: 0.025

  goal_distance_bias: 150.0
  path_distance_bias: 180.0
  occdist_scale: 0.05

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05

  forward_point_distance: 0.05

  scaling_speed: 0.25
  max_scaling_factor: 0.25

  vx_samples: 3
  vy_samples: 10
  vtheta_samples: 20

  sim_period: 0.1

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1

  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
