global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  inflate_unknown: true
  static_map: true
  rolling_window: false
  resolution: 0.01
  footprint_padding: 0.02
  plugins:
    - name: static_layer
      type: "costmap_2d::StaticLayer"
      output: "screen"
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
      output: "screen"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
      output: "screen"
