shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 8.0

planner_frequency: 5.0
planner_patience: 13.0

oscillation_timeout: 5.0
oscillation_distance: 0.2

base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_global_planner: "global_planner/GlobalPlanner" 

recovery_behavior_enabled: true
clearing_rotation_allowed: false

# recovery_behaviors:
#   - name: 'conservative_reset'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
#   - name: 'aggressive_reset'
#     type: 'clear_costmap_recovery/ClearCostmapRecovery'
# conservative_reset:
#   reset_distance: 0.1
#   layer_names: ['obstacle_layer']
# aggressive_reset:
#   reset_distance: 0.0
#   layer_names: ['obstacle_layer']